changes to schemas for reference pixels
spacetelescope/rad pull request #112
Opened 2022-02-01 14:08 UTC by cshanahan1

Changes to the schemas for the level 1 and 2 output files

The level 1 file has a science data array that includes the border reference pixels, and a separate array for the amp 33 reference pixels.

The level 2 file has a science data array that excludes the reference pixels, 4 separate arrays for the top, bottom, left, and right reference pixels. There is no amp 33 reference pixels array in this file.

Is there a way to specify the expected size of the file when one of the dimensions is variable. For example, a [???, 4096, 4022] array? Also, should the border reference pixel arrays include the overlap regions in the corners?

2022-02-01 15:27 UTC, PaulHuwe commented
We are not specifying array lengths in RAD at this moment. Generally, we implement those default values in the corresponding maker utility in roman_datamodels.

2022-02-01 15:33 UTC, gardner358 approved these changes

2022-02-01 15:37 UTC, cshanahan1 commented
just curious, why is 'var_flat' not a required property in the level 2 file?

2022-02-01 15:51 UTC, PaulHuwe commented
> just curious, why is 'var_flat' not a required property in the level 2 file?

Because Level 2 is created before the flat step.

2022-02-01 15:52 UTC, cshanahan1 commented
> > just curious, why is 'var_flat' not a required property in the level 2 file?
> 
> Because Level 2 is created before the flat step.

Should that property not be in the schema at all then?

2022-02-01 15:53 UTC, PaulHuwe commented
> > > just curious, why is 'var_flat' not a required property in the level 2 file?
> > 
> > 
> > Because Level 2 is created before the flat step.
> 
> Should that property not be in the schema at all then?

It should be there because the output of the flat step is a level 2 file.

2022-02-01 16:57 UTC, ddavis-stsci approved these changes
Looks good.

2022-02-07 20:48 UTC, nden reviewed
Looks good so far. Needs the new changes to the `ramp` schema.

2022-02-07 20:48 UTC, nden commented on src/rad/resources/schemas/wfi_image-1.0.0.yaml
> +        ndim: 2
Because these arrays are copied from the raw data and propagated, they will be cubes.

2022-02-07 20:48 UTC, nden commented on src/rad/resources/schemas/wfi_image-1.0.0.yaml
> +               border_ref_pix_right, border_ref_pix_top, border_ref_pix_bottom, cal_logs]
The `amp33` array will be present in the L2 files as well.

2022-02-07 20:48 UTC, nden commented on src/rad/resources/schemas/wfi_image-1.0.0.yaml
> +               border_ref_pix_right, border_ref_pix_top, border_ref_pix_bottom, cal_logs]
And the new decision to add the dq border arrays, means 4 more 2D arrays cut from the dq array.

2022-02-11 13:59 UTC, nden requested changes
Requested one `dtype` change for the border dq arrays. The rest looks good to me.

2022-02-11 16:01 UTC, nden approved these changes

2022-02-11 16:02 UTC, merged