Add test infrastructure and fix issues uncovered by tests
spacetelescope/rad pull request #14
Opened 2021-04-19 20:00 UTC by eslavich

This PR:

- Adds CI infrastructure
- Enables the asdf pytest plugin and adds basic tests of the asdf integration
- Adds a metaschema that validates `sdp` and `archive_catalog` properties in schemas
- Changes the URI prefix to `asdf://stsci.edu/datamodels/roman/<entity>/<name>`
- Fixes the pixelarea ref in wfi_image-1.0.0
- Updates some packaging details

Resolves #13
Resolves #10

2021-04-20 20:39 UTC, PaulHuwe requested changes

2021-04-20 20:39 UTC, PaulHuwe commented on src/rad/resources/schemas/rad_schema-1.0.0.yaml
> +# in object properties.
Is this comment supposed to be the same as the one on line 66?

2021-04-20 20:40 UTC, eslavich commented on src/rad/resources/manifests/datamodels-1.0.yaml
> +- tag_uri: tasdf://stsci.edu/datamodels/roman/tags/observation-1.0.0
Heh, oops.  No, it didn't, and it wouldn't since this is the primary source of the tag URI.

2021-04-20 20:41 UTC, eslavich commented on src/rad/resources/schemas/rad_schema-1.0.0.yaml
> +# in object properties.
Yup, it applies here too.  I duplicated it since is a separate section at a different indent level.

2021-04-21 00:22 UTC, eslavich commented on src/rad/resources/manifests/datamodels-1.0.yaml
> +- tag_uri: tasdf://stsci.edu/datamodels/roman/tags/observation-1.0.0
I fixed this and added an additional test that checks the tag URI prefix

2021-04-21 00:24 UTC, PaulHuwe approved these changes

2021-04-21 00:27 UTC, eslavich commented
Updated test results: https://github.com/eslavich/rad/actions/runs/768983483

2021-04-21 14:31 UTC, perrygreenfield reviewed
Very minor question, otherwise LGTM. I'm not yet qualified to review the CI and metaschema aspects yet. (Soon I hope on the former)[

2021-04-21 15:54 UTC, eslavich commented
Another test run: https://github.com/eslavich/rad/actions/runs/771249113

2021-04-21 15:55 UTC, perrygreenfield approved these changes
Now I can relax about the state of the world.

2021-04-21 15:56 UTC, merged