Rad 104: Enumerate Allowed Units for Science Data Quantities
spacetelescope/rad pull request #195
Opened 2022-12-06 18:25 UTC by PaulHuwe

Add units to the schemas for science data quantities to specify allowed values.

Notes:
- ASDF library requirement update is to capture enum fix.
- Some objects have multiple units supported due to unit conversion (e.g. gain application, etc.) happening to model objects. (It is possible this may need expanding depending on how quantities are converted.)
- I made the units of crmag counts / s, but would it be better to use magnitude from astropy instead?
- I am less confident about the units of the intermediate ramp arrays (slope, yint, etc.).

2022-12-06 19:45 UTC, ddavis-stsci commented
I think in general the CR magnitude is just electrons, not counts/s, see 
https://innerspace.stsci.edu/display/JWST/ODL+Documents?preview=%2F38143003%2F40240691%2FJWST-STScI-002468.pdf

2022-12-06 21:03 UTC, schlafly commented on src/rad/resources/schemas/ramp_fit_output-1.0.0.yaml
> +          enum: ["DN", "electron / s"]
My expectation is that yint and pedestal are the same and have the same units, so the comments above apply here as well.  I do not actually know what the distinction is between these two quantities.

2022-12-06 21:03 UTC, schlafly commented on src/rad/resources/schemas/ramp_fit_output-1.0.0.yaml
> +          enum: ["count / s"]
As Dave pointed out, this is DN.

2022-12-06 21:06 UTC, schlafly commented on src/rad/resources/schemas/ramp_fit_output-1.0.0.yaml
> +          enum: ["electron2 / s2"]
I think these are contributions to the variance in the slope.  So if slope really can have units of DN / s (I hope not?), then these should be allowed to have units of (DN / s)^2.

2022-12-06 21:57 UTC, tddesjardins commented on src/rad/resources/schemas/ramp-1.0.0.yaml
> +          enum: ["DN", "electron / s"]
Correct, the ramp model should be in DN, while the ramp_fit_output model should have a data array in units of electrons / s.

2022-12-06 22:00 UTC, tddesjardins commented on src/rad/resources/schemas/ramp-1.0.0.yaml
> +          enum: ["DN"]
It is correct for amp33 to be in DN. The weak lensing group requested that we keep the raw, untouched reference pixels (border + amp33) in the L2 files. So we do the reference pixel correction in DN, we remove the border, and we keep the originals in units of DN in their separate arrays.

2022-12-06 22:04 UTC, tddesjardins commented on src/rad/resources/schemas/ramp_fit_output-1.0.0.yaml
> +          enum: ["count / s"]
How is crmag being used in the pipeline? I don't think it comes out in L2 data does it? So it must be something between ramp_fit_output and wfi_image.

2022-12-06 22:05 UTC, tddesjardins commented on src/rad/resources/schemas/ramp_fit_output-1.0.0.yaml
> +          enum: ["DN", "electron / s"]
Similar to Eddie, I'm not sure what the difference between yint and pedestal is here, but that's a different issue. Eddie is correct about the units.

2022-12-06 22:07 UTC, tddesjardins commented on src/rad/resources/schemas/ramp_fit_output-1.0.0.yaml
> +          enum: ["electron2 / s2"]
If that was the case, then I agree. But since slope should only be electrons / s, then this is fine and slope should be fixed.

2022-12-06 22:09 UTC, schlafly commented on src/rad/resources/schemas/ramp-1.0.0.yaml
> +          enum: ["DN"]
Great, yeah, Stefano and I just hashed this out on #roman-dms-support.  I am skeptical that anyone will be able to use this information correctly without the L1 data, but we'll see.  Fine to keep only as DN.

2022-12-06 22:09 UTC, tddesjardins commented on src/rad/resources/schemas/ramp_fit_output-1.0.0.yaml
> +          enum: ["DN", "electron / s"]
Oh wait...okay, going back now that I'm thinking about it...is the order of operations here that the slope is computed in units of DN / s, and THEN the gain is applied to the slope? IF that's the case, then this is okay. The final L2 file will only be in units of electron / s, but there may be a brief window in the code in which it is in units of DN / s.

2022-12-06 22:12 UTC, tddesjardins reviewed
See my replies to Eddie's comments. There was nothing additional other than what he and Dave pointed out. If the situation is that there is a moment in the code where the slope is DN / s before the gain is applied, but the poisson variance hasn't been computed yet, then I think that's fine. I still have questions about the use of crmag and pedestal, but those shouldn't hold up the PR.

2022-12-06 22:17 UTC, schlafly commented on src/rad/resources/schemas/ramp_fit_output-1.0.0.yaml
> +          enum: ["DN", "electron / s"]
I don't know how we actually do it, but at least in the simulator it's important to apply the gain first so that one gets the right Poisson noise.

2022-12-06 22:19 UTC, schlafly commented on src/rad/resources/schemas/ramp_fit_output-1.0.0.yaml
> +          enum: ["count / s"]
I think it's auxiliary data it ramp fit output only.  It's not in the L2 data.

2022-12-07 00:17 UTC, PaulHuwe commented on src/rad/resources/schemas/ramp_fit_output-1.0.0.yaml
> +          enum: ["DN", "electron / s"]
Sensible. Applying change.

2022-12-07 00:17 UTC, PaulHuwe commented on src/rad/resources/schemas/ramp_fit_output-1.0.0.yaml
> +          enum: ["DN", "electron / s"]
Applied.

2022-12-07 00:18 UTC, PaulHuwe commented on src/rad/resources/schemas/ramp_fit_output-1.0.0.yaml
> +          enum: ["count / s"]
Already changed that one, thanks.

2022-12-07 00:23 UTC, PaulHuwe commented on src/rad/resources/schemas/ramp-1.0.0.yaml
> +          enum: ["DN", "electron / s"]
Changed.. I left it in incase the output of the step existed in RampModel at all before ImageModel, but I just double checked and it does not.

2022-12-07 00:23 UTC, PaulHuwe commented on src/rad/resources/schemas/ramp-1.0.0.yaml
> +          enum: ["DN", "electron / s"]
Changed.

2022-12-07 00:32 UTC, PaulHuwe commented
One thing to keep in mind when looking at units in these places is when the quantities get validated - which is why I left a few a bit more open (list vs just the expected output). With further regression style testing, these could be tightened.

2022-12-07 00:33 UTC, PaulHuwe commented on src/rad/resources/schemas/ramp_fit_output-1.0.0.yaml
> +          enum: ["DN", "electron / s"]
I only had it in DN in case the ramp step initialized the slope step array in STCAL with the DN input, but I just realized that it is stripped of units before passing to STCAL, so I can simplify these.

2022-12-07 13:56 UTC, schlafly commented on src/rad/resources/schemas/ramp_fit_output-1.0.0.yaml
> +          enum: ["DN"]
Ugh, sorry, yes, electron!  Otherwise these all look good now; thanks!

2022-12-12 15:27 UTC, kdupriestsci approved these changes
looks fine to me

2022-12-12 15:41 UTC, WilliamJamieson requested changes

2022-12-12 15:51 UTC, PaulHuwe commented on src/rad/resources/schemas/ramp_fit_output-1.0.0.yaml
> +          enum: ["count / s"]
This is actually outdated - already changed.

2022-12-14 21:25 UTC, schlafly approved these changes
Looks good to me.  I marked an extraneous comment I think we could remove.

2022-12-14 21:25 UTC, schlafly commented on src/rad/resources/schemas/ramp_fit_output-1.0.0.yaml
> +      # https://docs.astropy.org/en/stable/units/logarithmic_units.html
We can delete this comment.

2022-12-15 00:50 UTC, PaulHuwe commented on src/rad/resources/schemas/ramp_fit_output-1.0.0.yaml
> +      # https://docs.astropy.org/en/stable/units/logarithmic_units.html
```suggestion
      # Possibly use u.Magnitude instead?
      # https://docs.astropy.org/en/stable/units/logarithmic_units.html
```

2022-12-15 00:55 UTC, PaulHuwe commented on src/rad/resources/schemas/ramp_fit_output-1.0.0.yaml
> +      # https://docs.astropy.org/en/stable/units/logarithmic_units.html
Removed.

2022-12-15 00:59 UTC, merged