Fix minor discrepancies
spacetelescope/rad pull request #267
Opened 2023-05-24 18:49 UTC by WilliamJamieson

Closes #260

I have been noting some discrepancies, which @PaulHuwe turned into issue #260. I have since found a couple of other ones. This pull request resolves all the ones I have found so far.

**Checklist**
- [ ] Schema changes discussed at RAD Review Board meeting
- [ ] Added entry in `CHANGES.rst` under the corresponding subsection
- [ ] Updated relevant roman_datamodels utilities and tests
- [ ] Passed romancal regression testing on Jenkins / PLWishMaster. Link: https://plwishmaster.stsci.edu:8081/job/RT/job/romancal/XXX/

2023-05-24 18:53 UTC, WilliamJamieson commented on src/rad/resources/schemas/exposure-1.0.0.yaml
> +    type: integer
To match that `roman_datamodels` sets this as an integer (which is a number) and the note for the archive data that it is in-fact an integer.

2023-05-24 18:53 UTC, WilliamJamieson commented on src/rad/resources/schemas/guidewindow-1.0.0.yaml
> +              destination: [GuideWindow.gw_science_file_source]
@ddavis-stsci noted this in the issue.

2023-05-24 18:55 UTC, WilliamJamieson commented on src/rad/resources/schemas/ramp-1.0.0.yaml
> +properties:
The only change actually made here is to remove the wrapping `allOf`. This because it was not combining another schema in at this level and it is wrapping a regular object.

2023-05-24 18:56 UTC, WilliamJamieson commented on src/rad/resources/schemas/ramp-1.0.0.yaml
> +      - $ref: common-1.0.0
This all of could probably be removed too. @eslavich, is this correct? I know the `tagged_scalars` needed this to avoid issues with future versions of ASDF.

2023-05-24 18:57 UTC, WilliamJamieson commented on src/rad/resources/schemas/ramp_fit_output-1.0.0.yaml
> +properties:
Same as for `ramp-1.0.0`

2023-05-24 18:58 UTC, WilliamJamieson commented on src/rad/resources/schemas/reference_files/ref_common-1.0.0.yaml
> +properties:
Same as for `ramp-1.0.0`

2023-05-24 18:59 UTC, WilliamJamieson commented on src/rad/resources/schemas/reference_files/ref_exposure_type-1.0.0.yaml
> +          $ref: ../exposure_type-1.0.0
The title added was identical to the referenced schema and the `allOf` combiner is not needed here.

2023-05-24 18:59 UTC, WilliamJamieson commented on src/rad/resources/schemas/reference_files/ref_optical_element-1.0.0.yaml
> +        $ref: ../wfi_optical_element-1.0.0
`allOf` is not needed to combine anything

2023-05-24 19:54 UTC, kdupriestsci approved these changes

2023-05-25 03:45 UTC, PaulHuwe approved these changes
LGTM modulo the reply from @eslavich

2023-06-01 13:37 UTC, WilliamJamieson commented on src/rad/resources/schemas/ramp-1.0.0.yaml
> +      - $ref: common-1.0.0
According to #222, the issue is that when a `$ref` is present, all other properties at or below the level which it appears will be ignored (ie in the object in question). See

https://datatracker.ietf.org/doc/html/draft-wright-json-schema-00#section-7

in the relevant json schema specifications.

This means that the `allOf` here can indeed be removed since it will not override anything else inside the `meta` object (as it is the only thing)

2023-06-01 14:14 UTC, WilliamJamieson commented on src/rad/resources/schemas/associations-1.0.0.yaml
> +      required: [name, members]
@PaulHuwe does this look better for you. This expressly indicates that:

- `products` is a list of "dictionaries" (with specified keys/item entries).
	- Each of those dictionaries has a `name`-"string" pair and a `members`-"list" pair.
	- `members` is also a list of "dictionaries"
		-  Again each of these dictionaries is a specification of an object.

I feel this is much more clear than the current `allOf` combiners which were basically forcing the same thing, but not being very explicit about what one would actually see.

2023-06-04 19:26 UTC, PaulHuwe requested changes
LGTM - can you add the regression test link, please? (RomanCAL's repo is now up to date.

2023-06-04 19:26 UTC, PaulHuwe commented on src/rad/resources/schemas/associations-1.0.0.yaml
> +      required: [name, members]
👍🏻

2023-06-04 19:26 UTC, PaulHuwe commented on src/rad/resources/schemas/exposure-1.0.0.yaml
> +    type: integer
👍🏻

2023-06-04 19:26 UTC, PaulHuwe commented on src/rad/resources/schemas/guidewindow-1.0.0.yaml
> +              destination: [GuideWindow.gw_science_file_source]
👍🏻

2023-06-04 19:26 UTC, PaulHuwe commented on src/rad/resources/schemas/ramp-1.0.0.yaml
> +properties:
👍🏻

2023-06-04 19:26 UTC, PaulHuwe commented on src/rad/resources/schemas/ramp_fit_output-1.0.0.yaml
> +properties:
👍🏻

2023-06-04 19:26 UTC, PaulHuwe commented on src/rad/resources/schemas/reference_files/dark-1.0.0.yaml
> +            type: string
👍🏻

2023-06-04 19:26 UTC, PaulHuwe commented on src/rad/resources/schemas/reference_files/ref_common-1.0.0.yaml
> +properties:
👍🏻

2023-06-04 19:26 UTC, PaulHuwe commented on src/rad/resources/schemas/reference_files/ref_exposure_type-1.0.0.yaml
> +          $ref: ../exposure_type-1.0.0
👍🏻

2023-06-04 19:26 UTC, PaulHuwe commented on src/rad/resources/schemas/reference_files/ref_optical_element-1.0.0.yaml
> +        $ref: ../wfi_optical_element-1.0.0
👍🏻

2023-06-05 15:28 UTC, merged