Bugfix for `inverse_linearity-1.0.0` `reftype`
spacetelescope/rad pull request #272
Opened 2023-06-02 14:24 UTC by WilliamJamieson

Resolves [RAD-126](https://jira.stsci.edu/browse/RAD-126)

Closes #271

This updates the `reftype` in the `inverse_linearity-1.0.0` schema to be compatible with CRDS. Additionally, it adds tests to the test suite to ensure future `reftype` values are CRDS compatible. 

**Checklist**
- [ ] Schema changes discussed at RAD Review Board meeting
- [ ] Added entry in `CHANGES.rst` under the corresponding subsection
- [ ] Updated relevant roman_datamodels utilities and tests
- [ ] Passed romancal regression testing on Jenkins / PLWishMaster. Link: https://plwishmaster.stsci.edu:8081/job/RT/job/romancal/XXX/

2023-06-02 14:39 UTC, WilliamJamieson commented on src/rad/resources/schemas/reference_files/inverse_linearity-1.0.0.yaml
> +            enum: [INVERSE-LINEARITY]
Note `INVERSELINEARITY` is also valid, please let me know which is better.

2023-06-02 14:46 UTC, WilliamJamieson commented on tests/test_schemas.py
> +    assert is_crds_name(f"roman_wfi_{reftype.lower()}_0000.asdf")
CRDS requires a full file name. So I made up one that is valid around the inserted reftype.

2023-06-02 14:47 UTC, WilliamJamieson commented on tests/test_schemas.py
> +            return sub_schema["properties"]["reftype"]["enum"][0]
The `reftype` location within the `meta` `allOf` combiner is inconsistent across all of the reference_files because they have differing numbers of entries in it.

2023-06-03 14:25 UTC, nden commented on src/rad/resources/schemas/reference_files/inverse_linearity-1.0.0.yaml
> +            enum: [INVERSE-LINEARITY]
My recollection is it needs to be one word, i.e. I wasn't aware `INVERSE-LINEARITY` works. Apparently it passes tests though. For consistency I would vote for `INVERSELINEARITY`

2023-06-03 14:25 UTC, nden commented on pyproject.toml
> +    'crds>=11.16.16',
We don't expect we'll need to add many new reference types (or any?) so this may be a heavy test requirement. Others should chime in whether to have this test and dependency (though really only test dependency) in RAD.

2023-06-04 19:33 UTC, PaulHuwe requested changes
LGTM with the vote for INVERSELINEARITY.

2023-06-04 19:33 UTC, PaulHuwe commented on pyproject.toml
> +    'crds>=11.16.16',
I do not mind the dependency. Will we be adding any ref-like files for L3? (Thinking MA Tables or other association type stuff?)

2023-06-04 19:33 UTC, PaulHuwe commented on src/rad/resources/schemas/reference_files/inverse_linearity-1.0.0.yaml
> +            enum: [INVERSE-LINEARITY]
I prefer INVERSELINEARITY, we haven't been separating multiple words (e.g. READNOISE).

2023-06-05 15:54 UTC, nden commented on pyproject.toml
> +    'crds>=11.16.16',
There are no L3 reference files (at least for now). There might be par files but that's not confirmed yet.

2023-06-06 17:14 UTC, PaulHuwe approved these changes
LGTM

2023-06-06 17:17 UTC, nden approved these changes

2023-06-06 17:33 UTC, merged