Updates for release 0.18.
spacetelescope/rad pull request #337
Opened 2023-11-03 01:34 UTC by PaulHuwe

Resolves [RAD-nnnn](https://jira.stsci.edu/browse/RAD-nnnn)

Closes #

This PR addresses changes needed for release 0.18.

**Checklist**
- [ ] Schema changes discussed at RAD Review Board meeting
- [ ] Added entry in `CHANGES.rst` under the corresponding subsection
- [ ] Updated relevant roman_datamodels utilities and tests
- [ ] Passed romancal regression testing on Jenkins / PLWishMaster. Link: https://plwishmaster.stsci.edu:8081/job/RT/job/romancal/XXX/

2023-11-06 14:01 UTC, WilliamJamieson requested changes
There are a couple of spurious change which have made it into this PR. If we want these as part of the 0.18 release, then they should be placed in a separate PR which is merged prior to this one.

2023-11-06 16:39 UTC, PaulHuwe commented on src/rad/resources/schemas/exposure-1.0.0.yaml
> +      destination: [ScienceCommon.exposure_truncated]
Fixed by removing the Version uptick and updating the PR text.

2023-11-06 16:39 UTC, PaulHuwe commented on src/rad/resources/schemas/reference_files/dark-1.0.0.yaml
> +required: [meta, data, dq, dark_slope, dark_slope_error]
Fixed by removing the Version uptick and updating the PR text.

2023-11-06 16:47 UTC, WilliamJamieson approved these changes

2023-11-06 17:44 UTC, merged

2023-11-14 16:39 UTC, kdupriestsci reviewed
looks ok