Add WCS to schemas
spacetelescope/rad pull request #351
Opened 2024-01-10 15:02 UTC by nden

Resolves [RAD-nnnn](https://jira.stsci.edu/browse/RAD-nnnn)

Closes #

This PR addresses ...

**Checklist**
- [ ] Schema changes discussed at RAD Review Board meeting
- [ ] Added entry in `CHANGES.rst` under the corresponding subsection
- [ ] Updated relevant roman_datamodels utilities and tests
- [ ] Passed romancal regression testing on Jenkins / PLWishMaster. Link: https://plwishmaster.stsci.edu:8081/job/RT/job/romancal/XXX/

2024-01-10 18:10 UTC, ddavis-stsci approved these changes
LGTM

2024-01-11 15:33 UTC, braingram commented on src/rad/resources/schemas/wfi_image-1.0.0.yaml
> +              - tag: tag:stsci.edu:gwcs/wcs-1.0.0
@nden Here's the PR that added tag 'wildcard' support:
https://github.com/asdf-format/asdf/pull/858

I am not immediately finding usage of this within rad (I was hoping to point to an existing example).

If a wildcard seems worthwhile here one option would be to restrict it to only "wcs-1.x.x" versions (in case there is a "2.0.0" that breaks things.
```suggestion
              - tag: tag:stsci.edu:gwcs/wcs-1.*
```
The more liberal option would be to use "wcs-*". I did not test either of these locally so I'm not sure if there are other issues that might be caused by the use of a wildcard here.

2024-01-12 14:13 UTC, nden commented on src/rad/resources/schemas/wfi_image-1.0.0.yaml
> +              - tag: tag:stsci.edu:gwcs/wcs-1.0.0
Thanks !This works and regression tests now pass. Reading files with various WCS versions works as well.

2024-01-12 14:14 UTC, nden commented
Passing regression tests
https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/550/

2024-01-16 14:40 UTC, WilliamJamieson requested changes

2024-01-16 14:40 UTC, WilliamJamieson commented on src/rad/resources/schemas/wfi_image-1.0.0.yaml
> +              - type: "null"
Why is this null? It is not a required field by the object.

2024-01-22 00:17 UTC, PaulHuwe approved these changes
LGTM

2024-01-22 13:36 UTC, nden commented on src/rad/resources/schemas/wfi_image-1.0.0.yaml
> +              - type: "null"
Thanks for pointing this out. It needs to be a required field.

2024-01-22 16:45 UTC, WilliamJamieson commented on src/rad/resources/schemas/wfi_image-1.0.0.yaml
> +              - type: "null"
Should it still be null, or do we always expect a gwcs object in the end?

2024-01-22 16:51 UTC, WilliamJamieson approved these changes

2024-01-22 16:52 UTC, nden commented
Merging -  assuming this doesn't need to be approved for the database team

2024-01-22 16:52 UTC, merged