Update the titles and descriptions to those provided by INS
spacetelescope/rad pull request #361
Opened 2024-01-23 18:56 UTC by WilliamJamieson

This PR updates all the field/schema titles and descriptions to those listed by INS in https://innerspace.stsci.edu/display/RI/ASDF+L1+and+L2+metadata+keyword+review+assignments.

**Checklist**
- [ ] Schema changes discussed at RAD Review Board meeting
- [ ] Added entry in `CHANGES.rst` under the corresponding subsection
- [ ] Updated relevant roman_datamodels utilities and tests
- [ ] Passed romancal regression testing on Jenkins / PLWishMaster. Link: https://plwishmaster.stsci.edu:8081/job/RT/job/romancal/XXX/

2024-01-23 19:00 UTC, WilliamJamieson commented
Note, any field keyword changes, removals, or additions should be done in a separate PR as that type of change will be much more invasive to romancal. Please do make notes here and I will build an issue detailing those changes once this PR is finalized.

2024-01-23 22:32 UTC, braingram commented on src/rad/resources/schemas/aperture-1.0.0.yaml
> +    description: |
```suggestion
    description: >-
```
What are your thoughts on using a [folded block with block chomping](https://yaml-multiline.info/) instead of a literal block so that the newlines in the description are stripped on read?

Using literal blocks `|` the `schema_info` contains newlines:
```python
> af.schema_info()['roman']['meta']['aperture']['name']['description'].info
'Science aperture used as defined in the Project\nReference Database (PRD).\n'
```
Switching to a folded block with block chomping `>-` strips the newlines:
```python
> af.schema_info()['roman']['meta']['aperture']['name']['description'].info
'Science aperture used as defined in the Project Reference Database (PRD).'
```

2024-01-23 22:51 UTC, WilliamJamieson commented on src/rad/resources/schemas/aperture-1.0.0.yaml
> +    description: |
Honestly it does not matter to me. That sort of detail is up to the RAD and Roman pipeline developers.

2024-01-24 15:09 UTC, kdupriestsci commented on src/rad/resources/schemas/exposure-1.0.0.yaml
> +    title: Frame Divisor (s)
I'm assuming (s) isn't units or it would appear at the beginning as [s]. If instead it's saying there may be one or many Frame Divisors then I think there shouldn't be a space: Frame Divisor(s)

2024-01-24 15:26 UTC, kdupriestsci commented on src/rad/resources/schemas/observation-1.0.0.yaml
> +      The defined range of the execution plan within the program is 01 to 99;
If the type is integer, then shouldn't the range be 1 to 99 instead of 01 to 99?  01 makes it sound like it's a string.

2024-01-24 15:26 UTC, kdupriestsci commented on src/rad/resources/schemas/observation-1.0.0.yaml
> +      The defined range of the pass number within the execution plan is 001 to
Same comment as abolve

2024-01-24 15:27 UTC, kdupriestsci commented on src/rad/resources/schemas/observation-1.0.0.yaml
> +      The defined range of the segment number within the pass is 001 to 999;
Same comment as above

2024-01-24 15:27 UTC, kdupriestsci commented on src/rad/resources/schemas/observation-1.0.0.yaml
> +      The defined range of the visit number within the observation is 001 to
Same comment as above

2024-01-24 15:28 UTC, kdupriestsci commented on src/rad/resources/schemas/observation-1.0.0.yaml
> +      and has a defined range of 01 to 99; included in obs_id as 'gg'.
Same comment as above

2024-01-24 15:28 UTC, kdupriestsci commented on src/rad/resources/schemas/observation-1.0.0.yaml
> +      The defined range of the assigned exposure number within the visit is 0001
same comment as above

2024-01-24 15:48 UTC, kdupriestsci commented on src/rad/resources/schemas/reference_files/linearity-1.0.0.yaml
> -    tag: tag:stsci.edu:asdf/core/ndarray-1.0.0
Was the tag removed in error?

2024-01-24 15:52 UTC, kdupriestsci commented on src/rad/resources/schemas/reference_files/wfi_img_photom-1.0.0.yaml
In other files you included the units at the end of the title.  Why is that not done here?

2024-01-31 15:39 UTC, schlafly commented on src/rad/resources/schemas/exposure-1.0.0.yaml
> +    title: Frame Divisor (s)
No, let's delete (s).

2024-01-31 15:49 UTC, schlafly commented on src/rad/resources/schemas/observation-1.0.0.yaml
> +      The defined range of the execution plan within the program is 01 to 99;
This is following the existing schema.  Let's not change the type.  I interpret the comment to be about how the file name translates to the integer; the file name includes a string that is 01-99; this is transformed to an integer between 1-99.  Likewise for the related cases later on.

2024-01-31 15:52 UTC, schlafly commented on src/rad/resources/schemas/rad_schema-1.0.0.yaml
> +  Data Format and archive catalog-related properties.
I had understood SDF to be science data formatting.  @PaulHuwe , can you confirm we should update this comment and the title of the "sdf" block below?

2024-01-31 16:34 UTC, schlafly commented on src/rad/resources/schemas/ramp-1.0.0.yaml
> +      in the ramp.
Recommend:
title: Three-dimensional Data Quality Array For Each Resultant in Each Pixel
description: Three-dimensional data quality array indicating quality of each individual resultant for each pixel.

Note that there's nothing special about uneven here.

2024-01-31 16:34 UTC, schlafly commented on src/rad/resources/schemas/ramp_fit_output-1.0.0.yaml
> +      The magnitude of each segment that was flagged as having a cosmic ray hit.
We  don't use this so it's not really important to talk about it.  But as we haven't done the photometric calibration at this stage it is challenging for me to imagine that what is computed for Webb is in AB mags?

2024-01-31 16:34 UTC, schlafly commented on src/rad/resources/schemas/reference_files/flat-1.0.0.yaml
> +      sensitivity and distortions in the optical path.
I think the most important piece of information here is the ~sign; is the flattened data raw * flat or raw / flat?  Looking at the step, I know that it is raw / flat.  Suggest adding:
An image with uniform sensitivity to a constant surface brightness scene can be obtained by dividing the raw data by the flat field.

2024-01-31 16:34 UTC, schlafly commented on src/rad/resources/schemas/reference_files/ipc-1.0.0.yaml
> +      capacitance of neighboring pixels.
We don't actually do any correction here.  Suggest:
The kernel by which a signal recorded by an idealized detector lacking IPC needs to be convolved in order to obtain the IPC-affected signal recorded by a realistic detector.

2024-01-31 16:34 UTC, schlafly commented on src/rad/resources/schemas/reference_files/pixelarea-1.0.0.yaml
> +                  The nominal pixel area in steradians.
Does anyone know what the nominal pixel area is meant to represent?  Is it a per SCA quantity or a per array quantity?  Is it roughly the area of the central pixel or the average area of the pixels?  @tddesjardins

2024-01-31 16:34 UTC, schlafly commented on src/rad/resources/schemas/reference_files/readnoise-1.0.0.yaml
> +      expected noise in each pixel.
Add (DN) ?  Those are the units here.

2024-01-31 16:34 UTC, schlafly commented on src/rad/resources/schemas/target-1.0.0.yaml
> +      exposure.
Are things like the midpoint of the exposure relevant here?  My impression is that this schema comes from the proposal time, before the midpoint of the exposure is known?  @tddesjardins .  There's also an "uncertainty" field below that's confusing to me conceptually; I don't think we're supposed to be doing astrometry on a particular source and feeding it back into the metadata, and instead are supposed to be ingesting a field from APT.  Insofar as we do have an uncertainty in RA it would be good to know if that uncertainty is in "ra" or "ra * cos(dec)".

2024-01-31 16:48 UTC, braingram commented on src/rad/resources/schemas/aperture-1.0.0.yaml
> +    description: |
Yup, switching `|` to `>` would replace the internal new line characters with spaces (`>-` would also strip the trailing newline). This also applies to `title` and possibly other descriptive fields.

2024-01-31 16:56 UTC, WilliamJamieson commented on src/rad/resources/schemas/aperture-1.0.0.yaml
> +    description: |
I think this is a discussion for a separate set of changes. It can happen before these changes are merged, in which case this PR can be updated to match that style, or after this PR. However, the specifics of which to use distracts from the main point of these changes, which are to update the schemas with the titles and descriptions provided by INS.

2024-02-09 18:47 UTC, PaulHuwe commented on src/rad/resources/schemas/rad_schema-1.0.0.yaml
> +  Data Format and archive catalog-related properties.
I can confirm that it is Science Data Formatting

2024-02-09 20:13 UTC, WilliamJamieson commented on src/rad/resources/schemas/rad_schema-1.0.0.yaml
> +  Data Format and archive catalog-related properties.
If someone can update this on confluence that would be great.

2024-02-10 03:05 UTC, PaulHuwe requested changes

2024-02-10 03:05 UTC, PaulHuwe commented on src/rad/resources/schemas/ramp-1.0.0.yaml
> +    title: Science Data Including Border Reference Pixels
```suggestion
    title: Science Data Including Border Reference Pixels (DN, electrons)
```

2024-02-10 03:05 UTC, PaulHuwe commented on src/rad/resources/schemas/ramp-1.0.0.yaml
> +    title: Amp 33 Reference Pixel Data
```suggestion
    title: Amp 33 Reference Pixel Data (DN)
```

2024-02-10 03:05 UTC, PaulHuwe commented on src/rad/resources/schemas/ramp-1.0.0.yaml
> +      Amplifier 33 Reference Pixel Data.
```suggestion
      Amplifier 33 Reference Pixel Data.
```
```suggestion
      Amplifier 33 Reference Pixel Data in units of DN.
```

2024-02-10 03:05 UTC, PaulHuwe commented on src/rad/resources/schemas/ramp-1.0.0.yaml
> +      perspective.
```suggestion
      perspective in units of DN.
```

2024-02-10 03:05 UTC, PaulHuwe commented on src/rad/resources/schemas/ramp-1.0.0.yaml
> +      instrument's perspective.
```suggestion
      instrument's perspective in units of DN.
```

2024-02-10 03:05 UTC, PaulHuwe commented on src/rad/resources/schemas/ramp-1.0.0.yaml
> +    title: Border Reference Pixels on the Top of the Detector
```suggestion
    title: Border Reference Pixels on the Top of the Detector (DN)
```

2024-02-10 03:05 UTC, PaulHuwe commented on src/rad/resources/schemas/ramp-1.0.0.yaml
> +      Border Reference Pixels on the Top of the Detector.
```suggestion
      Border Reference Pixels on the Top of the Detector in units of DN.
```

2024-02-10 03:05 UTC, PaulHuwe commented on src/rad/resources/schemas/ramp-1.0.0.yaml
> +    title: Border Reference Pixels on the Bottom of the Detector
```suggestion
    title: Border Reference Pixels on the Bottom of the Detector (DN)
```

2024-02-10 03:05 UTC, PaulHuwe commented on src/rad/resources/schemas/ramp-1.0.0.yaml
> +      Border Reference Pixels on the Bottom of the Detector.
```suggestion
      Border Reference Pixels on the Bottom of the Detector in units of DN.
```

2024-02-23 19:23 UTC, schlafly commented
Since this ultimately just updates titles and descriptions, I'm just going to go ahead and approve it and we can take up further changes in subsequent PRs.

2024-02-23 19:23 UTC, schlafly approved these changes

2024-02-26 20:37 UTC, PaulHuwe approved these changes
Seconding @schlafly 's comment.

2024-02-26 20:37 UTC, merged

2024-02-26 20:37 UTC, kdupriestsci commented on src/rad/resources/schemas/wfi_image-1.0.0.yaml
> -    tag: tag:stsci.edu:asdf/core/ndarray-1.*
Did you mean to remove tag here?