Adding schema for Source Catalog
spacetelescope/rad pull request #374
Opened 2024-02-14 19:03 UTC by bmorris3

### (work in progress)

Resolves [RCAL-764](https://jira.stsci.edu/browse/RCAL-764)

This PR implements a basic schema for the output from the Source Catalog Step being developed in https://github.com/spacetelescope/romancal/pull/1102. Meetings in the next week or so will determine which fields should exist here.

**Checklist**
- [ ] Schema changes discussed at RAD Review Board meeting
- [ ] Added entry in `CHANGES.rst` under the corresponding subsection
- [ ] Updated relevant roman_datamodels utilities and tests
- [ ] Passed romancal regression testing on Jenkins / PLWishMaster. Link: https://plwishmaster.stsci.edu:8081/job/RT/job/romancal/XXX/

2024-02-14 19:08 UTC, WilliamJamieson requested changes
Initial comments

2024-02-14 19:08 UTC, WilliamJamieson commented on src/rad/resources/schemas/source_catalog-1.0.0.yaml
> +type: object
```suggestion
title: Source catalog generated by the Source Catalog Step.

datamodel_name: SourceCatalogModel
archive_meta: None

type: object
```

Makes it a bit easier to read.

2024-02-14 19:08 UTC, WilliamJamieson commented on src/rad/resources/schemas/source_catalog-1.0.0.yaml
> +properties:
General questions: Since this is a data model should it have a `meta` keyword? If so what metadata should be included.

2024-02-14 19:10 UTC, bmorris3 commented on src/rad/resources/schemas/source_catalog-1.0.0.yaml
> +properties:
I don't know yet – I'll follow up when I get directions from RTB.

2024-02-15 15:38 UTC, schlafly commented
Re possibly including metadata, when I make fits catalogs for other surveys, what I do is include the image header as the FITS header for the catalog.  You could also imagine including the step arguments so as to record some information about how the catalog was created.

For FITS the headers are usually pretty simple, but the asdf meta area can be more extensive so it's less clear to me that this makes as much sense there.  It's also nice if the files are easy to open; I'm not sure what number of dependencies one needs to bring in to open a file that contains one of our image headers.

2024-02-19 18:48 UTC, bmorris3 commented
In our last meeting, @schlafly checked if there was any downside to copying (parts of?) metadata from the L3 image used to produce the source catalog. @WilliamJamieson confirmed that ASDF would not complain if for example, GWCS was not installed, when loading a source catalog containing a copy of the metadata from its L3 image. 

So it sounds like we're likely to include some kind of metadata, though we don't know which yet.

2024-02-19 19:25 UTC, kdupriestsci commented on src/rad/resources/schemas/source_catalog-1.0.0.yaml
> +archive_meta: None
archive_meta is used to indicate this is the entry point for storing data in the db (e.g. wfi_image-1.0.0.yaml, guidewindow-1.0.0.yaml, etc.)  Is this such a file?

2024-02-19 20:19 UTC, bmorris3 commented on src/rad/resources/schemas/source_catalog-1.0.0.yaml
> +archive_meta: None
The honest answer is: I don't know. I'm waiting on instructions from RTB on these specs.

2024-02-20 16:08 UTC, WilliamJamieson commented on src/rad/resources/schemas/source_catalog-1.0.0.yaml
> +propertyOrder: [meta, source_catalog]
```suggestion
required: [source_catalog]
flowStyle: block
propertyOrder: [source_catalog]
```
This will fix the broken tests for now.

2024-02-20 16:47 UTC, bmorris3 commented on src/rad/resources/schemas/source_catalog-1.0.0.yaml
> +propertyOrder: [meta, source_catalog]
I wouldn't have figured this out quickly without you. Thank you 🙏🏻

2024-02-26 14:38 UTC, nden reviewed
I wrote what I think the initial metadata for these two schemas should be.
We can change/improve the metadata when we have more information.

2024-02-26 14:38 UTC, nden commented on src/rad/resources/schemas/segmentation_map-1.0.0.yaml
> +    anyOf:
```suggestion
    allOf:
```

2024-02-26 14:38 UTC, nden commented on src/rad/resources/schemas/segmentation_map-1.0.0.yaml
> +      - $ref: common-1.0.0
I don't think we need all of `common` here. In the absence of direction what to do I will list what I think we need to add to the metadata.
- remove `common`

2024-02-26 14:38 UTC, nden commented on src/rad/resources/schemas/segmentation_map-1.0.0.yaml
> +            type: string
Under properties add
- `basic`
- `coordinates`
- `wfi_optical_element`
- `program`
- `visit` (if a visit level catalog)

remove `filename` as it is included in `basic`

2024-02-26 14:38 UTC, nden commented on src/rad/resources/schemas/source_catalog-1.0.0.yaml
> +            type: string
I think this should follow what the `segmentation_map` schema includes.

2024-02-26 21:06 UTC, kdupriestsci commented on src/rad/resources/schemas/source_catalog-1.0.0.yaml
> +archive_meta: None
@nden I'm not sure what you mean by "at the level of wfi_image".  If they are their own files and not part of the wfi_image file then having the archive_meta: None is correct (we are not yet assigning a value to this keyword yet, we're just checking for its existence.

Please note that we don't have filetypes for Segmentation Maps or Source Catalogs in the archive (unless they're going under a different name), so this will require coordination with the db (either Azure or Oak, depending on who's doing it).

2024-02-27 14:19 UTC, nden commented on src/rad/resources/schemas/source_catalog-1.0.0.yaml
> +archive_meta: None
@kdupriestsci Sorry for the bad terminology. By "at the same level as wfi_image" I meant that these will be separate files. And thanks for clarifying the correct value in this case is `None`.

@ddavis-stsci @schlafly Could you coordinate with the rest of the team the work on the filetypes in the DB?

2024-02-27 14:21 UTC, nden commented
Of course this is the schema for the files so you can't really assign catalog.meta = image.meta but need to define them. Might as well figure out which parts make sense to be included.

2024-02-27 16:48 UTC, schlafly commented
I'm not good at reading rad schemas---I think we should try to follow the image metadata structure if we do this, and I think I read this schema as saying e.g. that the engineering_quality will be accessible as meta.engineering_quality.  Meanwhile for the images it'sat meta.visit.engineering_quality.

For L2 catalogs, the most important metadata to bring over is the photometry table that does the unit conversions; let's bring that as well.  But for L3 catalogs we don't need that.  Optional?

The next most important thing is the WCS in my opinion, so let's copy that too.

Then it becomes deeply unclear to me what we need.  'instrument' for the detector and 'exposure' for the times would cover most things.  Those are both L2s that we would make optional?

Another approach would just be to do something like one metadata keyword "image_filename" which is the filename of the image that the catalog was run on, and another metadata keyword "image_metadata" that is just given as an "object" and is identically the L2 / L3 image schema copied over, trying to avoid making a new set of metadata we need to separately track and copy...

2024-02-27 18:53 UTC, ddavis-stsci commented on src/rad/resources/schemas/source_catalog-1.0.0.yaml
> +archive_meta: None
We should bring this up in the RAD group but I think the correct filetype will be "Science WFI Level 4".

2024-02-29 16:48 UTC, PaulHuwe commented on src/rad/resources/schemas/source_catalog-1.0.0.yaml
> +  meta:
Could you please put meta above the binary contents for both this and `segmentation_map-1.0.0.yaml`?

2024-03-04 19:12 UTC, bmorris3 commented on src/rad/resources/schemas/source_catalog-1.0.0.yaml
> +  meta:
Yikes, order matters?

2024-03-05 22:20 UTC, PaulHuwe commented on src/rad/resources/schemas/source_catalog-1.0.0.yaml
> +  meta:
Doesn't matter code-wise (nor in the end file, you.. you set that order below). More about readability of schemas.

2024-03-29 12:03 UTC, nden commented
Superseded by #393

2024-03-29 12:03 UTC, closed without merging