use `towncrier` to handle change log entries
spacetelescope/rad pull request #442
Opened 2024-09-10 14:32 UTC by zacharyburnett

Resolves [RAD-nnnn](https://jira.stsci.edu/browse/RAD-nnnn)

Closes #

This PR addresses ...

**Checklist**
- [ ] Schema changes discussed at RAD Review Board meeting
- [ ] Added entry in `CHANGES.rst` under the corresponding subsection
- [ ] Updated relevant roman_datamodels utilities and tests
- [ ] Passed romancal regression testing on Jenkins / PLWishMaster. Link: https://plwishmaster.stsci.edu:8081/job/RT/job/romancal/XXX/

2024-09-12 23:24 UTC, PaulHuwe commented
I thought the existing changelog file would be converted to JSON, which would then be used going forward. Did I misunderstand?

2024-09-13 13:24 UTC, zacharyburnett commented
> I thought the existing changelog file would be converted to JSON, which would then be used going forward. Did I misunderstand?

I don't know about that, I considered modifying the existing changelog entries to make the issue numbers have links to the GitHub issue but I'm not sure how useful old changelog entries are (or who looks at them). This would just change how new sections are added to `CHANGES.rst` upon release

2024-09-13 19:55 UTC, PaulHuwe requested changes
Just some formatting changes for future PRs.

2024-09-13 19:55 UTC, PaulHuwe commented on .github/pull_request_template.md
> +- [ ] update or add relevant `rad` tests
```suggestion
- [ ] Update or add relevant `rad` tests.
```

2024-09-13 19:55 UTC, PaulHuwe commented on .github/pull_request_template.md
> +- [ ] update relevant docstrings and / or `docs/` page
```suggestion
- [ ] Update relevant docstrings and / or `docs/` page.
```

2024-09-13 19:55 UTC, PaulHuwe commented on .github/pull_request_template.md
> +- [ ] Does this PR change schema?
```suggestion
- [ ] Does this PR change any schema files?
```

2024-09-13 19:55 UTC, PaulHuwe commented on .github/pull_request_template.md
> +  - [ ] schema changes were discussed at RAD Review Board meeting
```suggestion
  - [ ] Schema changes were discussed at RAD Review Board meeting.
```

2024-09-13 19:55 UTC, PaulHuwe commented on .github/pull_request_template.md
> +- [ ] Does this PR change any API used downstream? (if not, label with `no-changelog-entry-needed`)
```suggestion
- [ ] Does this PR change any API used downstream? (If not, label with `no-changelog-entry-needed`.)
```

2024-09-13 19:55 UTC, PaulHuwe commented on .github/pull_request_template.md
> +  - [ ] write news fragment(s) in `changes/`: `echo "changed something" > changes/<PR#>.<changetype>.rst` (see below for change types)
```suggestion
  - [ ] Write news fragment(s) in `changes/`: `echo "changed something" > changes/<PR#>.<changetype>.rst` (see below for change types).
```

2024-09-13 19:55 UTC, PaulHuwe commented on .github/pull_request_template.md
> +  - [ ] [start a `romancal` regression test](https://github.com/spacetelescope/RegressionTests/actions/workflows/romancal.yml) with this branch installed (`"git+https://github.com/<fork>/rad@<branch>
```suggestion
  - [ ] Start a `romancal` regression test (https://github.com/spacetelescope/RegressionTests/actions/workflows/romancal.yml) with this branch installed (`"git+https://github.com/<fork>/rad@<branch>"`).
```

2024-09-13 19:55 UTC, PaulHuwe commented on .github/pull_request_template.md
> +  - [ ] update relevant `roman_datamodels` utilities and tests
```suggestion
  - [ ] Update relevant `roman_datamodels` utilities and tests.
```

2024-09-13 19:55 UTC, PaulHuwe commented on .github/pull_request_template.md
> +<details><summary>news fragment change types...</summary>
```suggestion
<details><summary>News fragment change types:</summary>
```

2024-09-16 15:15 UTC, PaulHuwe approved these changes
LGTM

2024-09-16 16:21 UTC, merged