RAD-181: Update guide_star, instrument, and photometry schemas
spacetelescope/rad pull request #471
Opened 2024-10-08 19:07 UTC by PaulHuwe

Resolves [RAD-181](https://jira.stsci.edu/browse/RAD-181)

Closes #470 

This PR update guide_star, instrument, and photometry schemas.

## Tasks
- [ ] Update or add relevant `rad` tests.
- [ ] Update relevant docstrings and / or `docs/` page.
- [x] Does this PR change any schema files?
  - [ ] Schema changes were discussed at RAD Review Board meeting.
- [ ] Does this PR change any API used downstream? (If not, label with `no-changelog-entry-needed`.)
  - [ ] Write news fragment(s) in `changes/`: `echo "changed something" > changes/<PR#>.<changetype>.rst` (see below for change types).
  - [ ] Start a `romancal` regression test (https://github.com/spacetelescope/RegressionTests/actions/workflows/romancal.yml) with this branch installed (`"git+https://github.com/<fork>/rad@<branch>"`).
  - [ ] Update relevant `roman_datamodels` utilities and tests.

<details><summary>News fragment change types:</summary>

- ``changes/<PR#>.feature.rst``: new feature
- ``changes/<PR#>.bugfix.rst``: fixes an issue
- ``changes/<PR#>.doc.rst``: documentation change
- ``changes/<PR#>.removal.rst``: deprecation or removal of public API
- ``changes/<PR#>.misc.rst``: infrastructure or miscellaneous change
</details

2024-10-11 20:48 UTC, kdupriestsci requested changes

2024-10-11 20:48 UTC, kdupriestsci commented on src/rad/resources/schemas/guidestar-1.0.0.yaml
> +      destination: [WFIExposure.dec, GuideWindow.dec]
I believe there's already a 'dec' field in WFIExposure and GuideWindow from file target-1.0.0.yaml

2024-10-11 20:48 UTC, kdupriestsci commented on src/rad/resources/schemas/guidestar-1.0.0.yaml
> +      destination: [WFIExposure.ra, GuideWindow.ra]
I believe there's already an "ra" field in WFIExposure and GuideWindow from file target-1.0.0.yaml

2024-10-11 20:48 UTC, kdupriestsci commented on src/rad/resources/schemas/guidestar-1.0.0.yaml
> +      destination: [WFIExposure.ra_uncertainty, GuideWindow.ra_uncertainty]
I believe there's already a 'ra_uncertainty' field in WFIExposure and GuideWindow from file target-1.0.0.yaml

2024-10-11 20:48 UTC, kdupriestsci commented on src/rad/resources/schemas/guidestar-1.0.0.yaml
> -      destination: [WFIExposure.gs_udec, GuideWindow.gs_udec]
I believe there's already a 'dec_uncertainty' field in WFIExposure and GuideWindow from file target-1.0.0.yaml

2024-10-11 20:48 UTC, kdupriestsci commented on src/rad/resources/schemas/guidestar-1.0.0.yaml
> +      destination: [WFIExposure.proper_motion_ra, GuideWindow.proper_motion_ra]
I believe there's already a 'proper_motion_ra' field in WFIExposure and GuideWindow from file target-1.0.0.yaml

2024-10-11 20:48 UTC, kdupriestsci commented on src/rad/resources/schemas/guidestar-1.0.0.yaml
> +      destination: [WFIExposure.proper_motion_dec, GuideWindow.proper_motion_dec]
I believe there's already a 'proper_motion_dec' field in WFIExposure and GuideWindow from file target-1.0.0.yaml

2024-10-15 14:13 UTC, schlafly approved these changes
This all looks fine to me, though of course I defer to Kim on the database side!  Note that this also does unit-dropping, which is in Mairan's PR as well, and the plan is to include some unit information in the schema but not to enforce it with the quantity tag.  No action needed here, just flagging that the unit-related changes will see churn & conflicts soon.

2024-10-15 19:43 UTC, PaulHuwe commented on src/rad/resources/schemas/guidestar-1.0.0.yaml
> +      destination: [WFIExposure.dec, GuideWindow.dec]
The `target-1.0.0.yaml` schema is being removed with this suite of PRs, so there should be no conflict.

2024-10-15 19:43 UTC, PaulHuwe commented on src/rad/resources/schemas/guidestar-1.0.0.yaml
> +      destination: [WFIExposure.ra_uncertainty, GuideWindow.ra_uncertainty]
The `target-1.0.0.yaml` schema is being removed with this suite of PRs, so there should be no conflict.

2024-10-15 19:44 UTC, PaulHuwe commented on src/rad/resources/schemas/guidestar-1.0.0.yaml
> -      destination: [WFIExposure.gs_udec, GuideWindow.gs_udec]
The `target-1.0.0.yaml` schema is being removed with this suite of PRs, so there should be no conflict.

2024-10-15 19:44 UTC, PaulHuwe commented on src/rad/resources/schemas/guidestar-1.0.0.yaml
> +      destination: [WFIExposure.proper_motion_ra, GuideWindow.proper_motion_ra]
The `target-1.0.0.yaml` schema is being removed with this suite of PRs, so there should be no conflict.

2024-10-15 19:44 UTC, PaulHuwe commented on src/rad/resources/schemas/guidestar-1.0.0.yaml
> +      destination: [WFIExposure.proper_motion_dec, GuideWindow.proper_motion_dec]
The `target-1.0.0.yaml` schema is being removed with this suite of PRs, so there should be no conflict.

2024-10-16 22:17 UTC, jbrookens approved these changes

2024-10-29 20:22 UTC, merged