RAD-92: Update visit, l1, and l2 attribute information
spacetelescope/rad pull request #481
Opened 2024-10-10 21:29 UTC by PaulHuwe

Resolves [RAD-92](https://jira.stsci.edu/browse/RAD-92)

Closes #184 

This PR updates visit, l1, and l2 attribute information

## Tasks
- [ ] Update or add relevant `rad` tests.
- [ ] Update relevant docstrings and / or `docs/` page.
- [x] Does this PR change any schema files?
  - [ ] Schema changes were discussed at RAD Review Board meeting.
- [ ] Does this PR change any API used downstream? (If not, label with `no-changelog-entry-needed`.)
  - [ ] Write news fragment(s) in `changes/`: `echo "changed something" > changes/<PR#>.<changetype>.rst` (see below for change types).
  - [ ] Start a `romancal` regression test (https://github.com/spacetelescope/RegressionTests/actions/workflows/romancal.yml) with this branch installed (`"git+https://github.com/<fork>/rad@<branch>"`).
  - [ ] Update relevant `roman_datamodels` utilities and tests.

<details><summary>News fragment change types:</summary>

- ``changes/<PR#>.feature.rst``: new feature
- ``changes/<PR#>.bugfix.rst``: fixes an issue
- ``changes/<PR#>.doc.rst``: documentation change
- ``changes/<PR#>.removal.rst``: deprecation or removal of public API
- ``changes/<PR#>.misc.rst``: infrastructure or miscellaneous change
</details

2024-10-11 01:51 UTC, PaulHuwe commented on src/rad/resources/schemas/wfi_image-1.0.0.yaml
> +            title: Calibration Logs
```suggestion
```

2024-10-11 01:52 UTC, PaulHuwe commented on src/rad/resources/schemas/wfi_image-1.0.0.yaml
> +              Calibration logs.
```suggestion
            description: |
              Calibration logs.
```

2024-10-11 01:53 UTC, PaulHuwe commented on src/rad/resources/schemas/wfi_image-1.0.0.yaml
> +            title: Tracker of Calibration Pipeline Steps
```suggestion
```

2024-10-14 17:54 UTC, kdupriestsci requested changes

2024-10-14 17:54 UTC, kdupriestsci commented on src/rad/resources/schemas/visit-1.0.0.yaml
> +                        SegmentationMap.engineering_quality]
The columns should be the same across all the tables. (I assume you want dither_primary_name?)

2024-10-15 15:29 UTC, schlafly commented on src/rad/resources/schemas/wfi_image-1.0.0.yaml
> +        datatype: uint16
@tddesjardins , I hadn't appreciated we were changing the type of these.  Presently the 4k by 4k pixels get converted to floats and treated ~the same up until ramp fitting, when these are separated from the science data.  That means treating them like floats for the purposes of this image.

That seems like the right behavior to me, and I read this change as saying we shouldn't do that and should instead ignore these pixels for dark subtraction, linearity correction, etc..  That would require more work in the pipeline and I wouldn't do it here.

@PaulHuwe , I'm writing this comment in the context of border_ref_pix_left, but it applies to the other border_pix as well.

It's also true that we treat the amp33 and other pixels differently.  The amp33 pixels do _not_ get the same dark subtraction, etc., that the other pixels do, since they're not actual pixels and it's not clear we could do anything meaningful here.  I think that's the right treatment as well, but it is awkward that the different reference pixels have different data types.

2024-10-15 16:55 UTC, tddesjardins commented on src/rad/resources/schemas/wfi_image-1.0.0.yaml
> +        datatype: uint16
I thought we were holding on to a version of the reference pixels that are uncalibrated, i.e., they have not been dark subtracted, linearity corrected, etc.? The IRRC is before any other calibration step, and the intent was that these arrays are copies of the untouched reference pixels (this was a request from specific science teams via the calibration working group). So I think these are supposed to be uint16 pixels in DN. You're right we carry them around a little longer and chop them off of the image after the classical linearity correction, but these are copies of the originals not the ones we chopped off.

2024-10-15 17:27 UTC, schlafly commented on src/rad/resources/schemas/wfi_image-1.0.0.yaml
> +        datatype: uint16
Ah!  Correct, indeed, thanks.  Okay, this looks fine, sorry!  I guess I register that I think carrying these on uncalibrated is somewhat silly but that's water under the bridge.

2024-10-20 00:20 UTC, PaulHuwe commented on src/rad/resources/schemas/visit-1.0.0.yaml
> +                        SegmentationMap.engineering_quality]
Thanks, fixed.

2024-10-29 20:30 UTC, PaulHuwe commented
Closing as all changes already merged.

2024-10-29 20:30 UTC, closed without merging