Remove basic from ref_common as well as reftype
spacetelescope/rad pull request #59
Opened 2021-07-01 20:47 UTC by perrygreenfield

Much of what is in basic is irrelevant to reference files and should not be required in reference files. This PR removes that $ref of basic, and transfers the presumably required attributes directly to ref_common (as I understand it, this includes filename, file_date, telescope, and origin; if not, please comment).

Also removed is reftype since each reference file schema should include this attribute with a single enum value.

This closes #54

2021-07-01 21:31 UTC, PaulHuwe requested changes

2021-07-01 21:31 UTC, PaulHuwe commented on src/rad/resources/schemas/reference_files/ref_common-1.0.0.yaml
> -             SATURATION, SUPERBIAS, TRAPDENSITY, TRAPPARS]
Is this being removed due to duplication? Accordingly, would we then need to add reftype to all the individual reference models in their propertyOrder & required lists?

2021-07-01 21:31 UTC, PaulHuwe commented on src/rad/resources/schemas/reference_files/ref_common-1.0.0.yaml
> +  required: [author, description, pedigree, useafter, filename, file_date, origin]
What about model_type?

2021-07-01 21:52 UTC, perrygreenfield commented on src/rad/resources/schemas/reference_files/ref_common-1.0.0.yaml
> +  required: [author, description, pedigree, useafter, filename, file_date, origin]
model_type was present for JWST since the FITS files don't have tags. The tag drives the model type in this case. It is redundant to the tag, and in any case, the tag is the primary indicator.

2021-07-01 21:53 UTC, perrygreenfield commented on src/rad/resources/schemas/reference_files/ref_common-1.0.0.yaml
> -             SATURATION, SUPERBIAS, TRAPDENSITY, TRAPPARS]
I see that it isn't but I forget the subtleties of where you can put required when references are used. I'll let him comment on that. Maybe he can suggest the best solution.

2021-07-01 22:38 UTC, PaulHuwe commented on src/rad/resources/schemas/reference_files/ref_common-1.0.0.yaml
> +  required: [author, description, pedigree, useafter, filename, file_date, origin]
If the tag is driving the model, should model_type be removed from basic as well?

2021-07-01 23:22 UTC, eslavich commented on src/rad/resources/schemas/reference_files/ref_common-1.0.0.yaml
> -             SATURATION, SUPERBIAS, TRAPDENSITY, TRAPPARS]
The `required` validator is independent of the individual property subschemas, so it should work fine to include reftype in the required list in this file.  But even so it might be worth keeping this much here:

```yaml
    reftype:
      title: Reference file type
      type: string
 ```
 
 mainly as documentation as to what reftype is supposed to be.  Without the enum list, so that doesn't need to be maintained.

2021-07-01 23:28 UTC, eslavich commented on src/rad/resources/schemas/reference_files/ref_common-1.0.0.yaml
> +    filename:
Does this need to be maintained by CRDS?  I mean, when CRDS receives a reference file submission and renames the file, should it also get into the file and update `meta.filename`?

2021-07-02 11:31 UTC, perrygreenfield commented on src/rad/resources/schemas/reference_files/ref_common-1.0.0.yaml
> +    filename:
I wondered about that as well, but when I asked @nden about this she said redcat required theses keywords (actually, I'm not exactly sure which of this set are required since I think I only asked specifically about file_date). I think she can answer this or tell us who can.

2021-07-02 11:32 UTC, perrygreenfield commented on src/rad/resources/schemas/reference_files/ref_common-1.0.0.yaml
> -             SATURATION, SUPERBIAS, TRAPDENSITY, TRAPPARS]
I think that is a good solution. I'll put that in.

2021-07-02 13:48 UTC, eslavich commented on src/rad/resources/schemas/reference_files/ref_common-1.0.0.yaml
> +    filename:
Matt says he's not sure where the requirement for meta.filename comes from and it sounds like it may not be necessary.  We have a meeting next week where I'll be able to ask more questions about it.

2021-07-08 16:38 UTC, PaulHuwe commented on src/rad/resources/schemas/reference_files/ref_common-1.0.0.yaml
> -             SATURATION, SUPERBIAS, TRAPDENSITY, TRAPPARS]
This is resolved for me.

2021-07-08 16:45 UTC, eslavich approved these changes
LGTM!

2021-07-08 16:52 UTC, PaulHuwe commented on src/rad/resources/schemas/reference_files/ref_common-1.0.0.yaml
> +  required: [author, description, pedigree, useafter, filename, file_date, origin]
@perrygreenfield ?

2021-07-08 16:53 UTC, PaulHuwe approved these changes
LGTM, though the question about model_type is unanswered.

2021-07-08 17:13 UTC, perrygreenfield commented on src/rad/resources/schemas/reference_files/ref_common-1.0.0.yaml
> +  required: [author, description, pedigree, useafter, filename, file_date, origin]
It should. I can do that in a few minutes.

2021-07-08 17:14 UTC, perrygreenfield commented on src/rad/resources/schemas/reference_files/ref_common-1.0.0.yaml
> +  required: [author, description, pedigree, useafter, filename, file_date, origin]
Remove it, that is.

2021-07-23 15:37 UTC, merged